### PR TITLE
Tika 1.11

### PR DESCRIPTION
**Pull request by gggeek**
Basically only tika.jar has been updated. All the rest are minor cleanups which should not have impact on the code

### CODE REVIEW

**Comment by xrow** [comment]
Thanks gg. I make it 1.7.

**Comment by gggeek** [comment]
Note: you can wait one or 2 days before tagging the release. I am testing it...

**Comment by xrow** [comment]
I will release again if you find something.

**Comment by gggeek** [comment]
ok good then

**Comment by paulborgermans** [comment]
The original version lives here:

https://github.com/paulborgermans/eztika

There are no more binaries distributed with the eztika extension, but there is a server mode that is a lot faster

**Comment by gggeek** [comment]
@paulborgermans nice to know! Can you add a composer.json and register it on packagist?

**Comment by gggeek** [comment]
Long time no see :-)

I have now updated the bundled tika to rev. 1.14.

care to merge and release as 1.8 ?

**Comment by xrow** [comment]
@gggeek 1.8 done. Thanks. Didn't we see us on the last conference? Besides you might have referred to @paulborgermans. I havn`t seen him for a while. I hope I will do sometime again.

**Comment by gggeek** [comment]
Thanks.
Indeed it was nice to see you at the conf. The reference to long time was just a cheesy pun on this PR being open for almost exactly 1 year :-)

**Comment by xrow** [comment]
Sorry I might have missed it. Next time just ping again. My inbox is always crazy...

**Pull request merged**
